### ISSUE TITLE
Ansible MODE missing leading 0 in promtail

### ISSUE THREAD

**Issue by YurkoWasHere** [polkachu/secure-server-setup#1]
Ansible's mode should be 0600 and 0755. Lack of leading 0 creates incorrect permission
https://github.com/polkachu/secure-server-setup/blob/main/roles/setup/tasks/install_promtail.yml#L44
https://github.com/polkachu/secure-server-setup/blob/main/roles/setup/tasks/install_promtail.yml#L59

**Comment by PolkachuIntern** [comment]
Great catch. Fix them all in this commit https://github.com/polkachu/secure-server-setup/commit/89685b2de5393adf090fa7084a4f849dfab6ffe3. Thanks very much.
